# Generated by Django 5.0.14 on 2026-09-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminprofile_auditlog_parentaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('clerk', 'Clerk')], default='admin', max_length=10),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='theme',
            field=models.CharField(choices=[('system', 'Match System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('pocket_money_deposit', 'Pocket Money Deposit'), ('pocket_money_withdrawal', 'Pocket Money Withdrawal'), ('pocket_money_deleted', 'Pocket Money Transaction Deleted')], max_length=30),
        ),
    ]
