# Generated by Django 5.0.14 on 2026-10-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminprofile_language_adminprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='website',
            field=models.URLField(blank=True, help_text='Shown on the student verification page, e.g. https://yourschool.ac.tz', null=True),
        ),
    ]
