# Generated by Django 5.0.14 on 2026-09-20 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='Staff account that registered this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_class',
            field=models.CharField(choices=[('form one', 'Form One'), ('form two', 'Form Two'), ('form three', 'Form Three'), ('form four', 'Form Four'), ('form five', 'Form Five'), ('form six', 'Form Six')], default='form one', max_length=20, verbose_name='Class / Grade'),
        ),
    ]
