# Generated by Django 5.0.14 on 2026-09-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_added_by_alter_student_grade_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_whatsapp',
            field=models.CharField(blank=True, help_text='Optional — used for WhatsApp notifications. Falls back to phone number if left blank.', max_length=20, null=True, verbose_name="Father's WhatsApp Number"),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Middle Name (Father's Name)"),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_whatsapp',
            field=models.CharField(blank=True, help_text='Optional — used for WhatsApp notifications. Falls back to phone number if left blank.', max_length=20, null=True, verbose_name="Mother's WhatsApp Number"),
        ),
    ]
