# Generated by Django 5.0.14 on 2026-09-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_importjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolloverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('january', 'January (O-level)'), ('june', 'June (A-level)')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('promoted_count', models.PositiveIntegerField(default=0)),
                ('graduated_count', models.PositiveIntegerField(default=0)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('event', 'year')},
            },
        ),
    ]
