# Generated by Django 5.0.14 on 2026-09-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Last valid day of this card. Blank = never expires (graduated).', null=True),
        ),
    ]
